language: python
python:
  - "3.9"
  - "3.11"
env: CFLAGS="-O0"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -e .
script: python setup.py test
after_success:
  - coveralls

# See: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false
